import { FileText, BarChart2, ShieldAlert, Sparkles, MoreHorizontal } from 'lucide-react';
import './Dashboard.css';

export function MainContent() {
  const recentReports = [
    { title: 'Q3 Financial Overview', desc: 'Generated by Edwin Antony', time: '2 hours ago', icon: <FileText size={16} /> },
    { title: 'User Growth Analytics', desc: 'Auto-generated report', time: '5 hours ago', icon: <BarChart2 size={16} /> },
    { title: 'Security Audit Log', desc: 'System generated', time: '1 day ago', icon: <ShieldAlert size={16} /> }
  ];

  const aiRecommendations = [
    { title: 'Optimize Storage', desc: 'You can save 12GB by clearing old logs.', icon: <Sparkles size={16} /> },
    { title: 'New Trend Detected', desc: 'User engagement is up 15% this week.', icon: <Sparkles size={16} /> }
  ];

  return (
    <div className="main-content-layout">
      
      {/* Left Column - 70% */}
      <div className="content-column">
        
        {/* Recent Reports */}
        <div className="content-card">
          <div className="content-card-header">
            <h3 className="content-card-title">Recent Reports</h3>
            <button className="content-card-action">View all</button>
          </div>
          <div>
            {recentReports.map((report, idx) => (
              <div key={idx} className="list-item">
                <div className="list-icon">{report.icon}</div>
                <div className="list-content">
                  <div className="list-title">{report.title}</div>
                  <div className="list-desc">{report.desc}</div>
                </div>
                <div className="list-meta">{report.time}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Usage Analytics Mock Chart */}
        <div className="content-card">
          <div className="content-card-header">
            <h3 className="content-card-title">Usage Analytics</h3>
            <button className="content-card-action">Export</button>
          </div>
          <div style={{ height: '200px', display: 'flex', alignItems: 'flex-end', gap: '8px', padding: '20px 0' }}>
            {/* Very simple mock bar chart using divs */}
            {[40, 70, 45, 90, 65, 80, 55, 100, 75, 85].map((height, i) => (
              <div key={i} style={{ 
                flex: 1, 
                backgroundColor: 'var(--primary-light)',
                height: `${height}%`,
                borderRadius: '4px 4px 0 0',
                transition: 'height 1s ease-out'
              }}>
                <div style={{
                  backgroundColor: 'var(--primary)',
                  height: '100%',
                  opacity: i === 7 ? 1 : 0.6,
                  borderRadius: 'inherit'
                }}></div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Right Column - 30% */}
      <div className="content-column">
        
        {/* Workspace Health */}
        <div className="content-card">
          <div className="content-card-header">
            <h3 className="content-card-title">Workspace Health</h3>
            <MoreHorizontal size={16} className="text-muted" />
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '16px' }}>
            <div style={{ width: '64px', height: '64px', borderRadius: '50%', border: '6px solid var(--success)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '18px', fontWeight: 'bold' }}>
              98
            </div>
            <div>
              <div style={{ fontWeight: 600, marginBottom: '4px' }}>Excellent Status</div>
              <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>All systems operational</div>
            </div>
          </div>
        </div>

        {/* AI Recommendations */}
        <div className="content-card">
          <div className="content-card-header">
            <h3 className="content-card-title">
              <Sparkles size={16} color="var(--primary)" /> AI Insights
            </h3>
          </div>
          <div>
            {aiRecommendations.map((rec, idx) => (
              <div key={idx} className="list-item" style={{ borderBottom: 'none' }}>
                <div className="list-icon" style={{ background: 'var(--primary-light)', color: 'var(--primary)' }}>
                  {rec.icon}
                </div>
                <div className="list-content">
                  <div className="list-title">{rec.title}</div>
                  <div className="list-desc">{rec.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Storage Usage */}
        <div className="content-card">
          <div className="content-card-header">
            <h3 className="content-card-title">Storage Usage</h3>
          </div>
          <div style={{ marginBottom: '8px', display: 'flex', justifyContent: 'space-between', fontSize: '13px' }}>
            <span style={{ fontWeight: 500 }}>45.2 GB used</span>
            <span style={{ color: 'var(--text-muted)' }}>100 GB total</span>
          </div>
          <div className="progress-container">
            <div className="progress-fill" style={{ width: '45.2%' }}></div>
          </div>
        </div>

      </div>

    </div>
  );
}
